server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
  application:
    name: testService
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.198.100:8848
        cluster-name: WH