spring:
  redis:
    host: 192.168.198.100
    port: 6379
    password: 123456
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: project-auth
          uri: lb://project-auth
          predicates:
            - Path=/auth/**
        # 系统模块
        - id: project-system
          uri: lb://project-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1

# 安全配置
security:
  # 验证码
  captcha:
    enabled: true
    type: math
  # 不校验白名单
  ignore:
    whites:
      - /auth/logout
      - /auth/login
      - /auth/register
      - /*/v2/api-docs
      - /csrf
